/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2018-10-09 07:29:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.*;
import java.util.*;
import com.domain.User;
import java.util.*;
import com.constant.OptTypeConstant;
import java.util.*;
import java.util.*;

public final class fiveMinutes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/index_header.jsp", Long.valueOf(1537954381700L));
    _jspx_dependants.put("/index_menu.jsp", Long.valueOf(1537954381711L));
    _jspx_dependants.put("/index_footer.jsp", Long.valueOf(1537954381693L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1537954381678L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("com.domain.User");
    _jspx_imports_classes.add("com.constant.OptTypeConstant");
    _jspx_imports_classes.add("org.json.JSONArray");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

	String startDate = (String) request.getAttribute("startDate");
	String endDate = (String) request.getAttribute("endDate");
	String y = "";
	String m = "";
	String d = "";
	if (startDate != null) {
		y = startDate.substring(0, 4);
		m = Integer.parseInt(startDate.substring(5, 7)) - 1 + "";
		d = startDate.substring(8, startDate.length());
	}
	
	JSONObject data_1 = (JSONObject)request.getAttribute("fiveOnlineData");
	JSONArray fiveOnlineData = new JSONArray();
	String fiveOnlineData_1 = "";
	String fiveOnlineData_2 = "";
	int curNum_1 = 0;
	int fiveminNum_1 = 0;
	int onehourNum_1 = 0;
	if (data_1 != null) {
		fiveOnlineData = (JSONArray) data_1.getJSONArray("dataList");
		JSONObject obj;
		int maxIndex = 0;
		int length = fiveOnlineData.length();
		for (int i = 0; i < length; i++) {
			obj = fiveOnlineData.getJSONObject(i);
			if (obj.has("num")) {
				fiveOnlineData_1 += obj.getString("num") + ",";
				maxIndex = i;
			}
			if (obj.has("num1")) {
				fiveOnlineData_2 += obj.getString("num1") + ",";
			}
		}
		
		if (length > maxIndex) {
			obj = fiveOnlineData.getJSONObject(maxIndex);
			curNum_1 = Integer.parseInt(obj.getString("num"));
		}
		
		if (length > maxIndex - 1 && maxIndex > 0) {
			obj = fiveOnlineData.getJSONObject(maxIndex - 1);
			fiveminNum_1 = Integer.parseInt(obj.getString("num"));
		}
		
		if (length > maxIndex - 13 && maxIndex > 12) {
			obj = fiveOnlineData.getJSONObject(maxIndex - 13);
			onehourNum_1 = Integer.parseInt(obj.getString("num"));
		}
	}
	String fiveminStr_1 = "";
	if (fiveminNum_1 == curNum_1) {
		fiveminStr_1 = fiveminNum_1 + "";
	} else if (fiveminNum_1 - curNum_1 > 0) {
		fiveminStr_1 = fiveminNum_1 + "<span class='grayicon icon-down'></span><font color='#c12121'>" + (fiveminNum_1 - curNum_1) + "</font>";
	} else if (fiveminNum_1 - curNum_1 < 0) {
		fiveminStr_1 = fiveminNum_1 + "<span class='grayicon icon-up'></span><font color='#3a963e'>" + (curNum_1 - fiveminNum_1) + "</font>";
	}
	
	String onehourStr_1 = "";
	if (onehourNum_1 == curNum_1) {
		onehourStr_1 = onehourNum_1 + "";
	} else if (onehourNum_1 - curNum_1 > 0) {
		onehourStr_1 = onehourNum_1 + "<span class='grayicon icon-down'></span><font color='#c12121'>" + (onehourNum_1 - curNum_1) + "</font>";
	} else if (onehourNum_1 - curNum_1 < 0) {
		onehourStr_1 = onehourNum_1 + "<span class='grayicon icon-up'></span><font color='#3a963e'>" + (curNum_1 - onehourNum_1) + "</font>";
	}
	
	int lastVal_1 = 0, lastVal_2 = 0, curVal = 0;
	JSONObject data_2 = (JSONObject)request.getAttribute("fiveRegisterData");
	JSONArray fiveRegisterData = new JSONArray();
	String fiveRegisterData_1 = "0,";
	String fiveRegisterData_2 = "0,";
	String fiveRegisterData_3 = "0,";
	String fiveRegisterData_4 = "0,";
	int curNum_2 = 0;
	int fiveminNum_2 = 0;
	int onehourNum_2 = 0;
	if (data_1 != null) {
		fiveRegisterData = (JSONArray) data_2.getJSONArray("dataList");
		JSONObject obj;
		int maxIndex = 0;
		int length = fiveRegisterData.length();
		for (int i = 1; i < fiveRegisterData.length(); i++) {
			obj = fiveRegisterData.getJSONObject(i);
			if (obj.has("num")) {
				curVal = Integer.parseInt(obj.getString("num"));
				fiveRegisterData_1 += curVal + ",";
				if (i % 3 == 0  || i == 287) {
					fiveRegisterData_3 += (curVal - lastVal_1) + ",";
					lastVal_1 = curVal;
				}
				maxIndex = i;
			}
				
			if (obj.has("num1")) {
				curVal = Integer.parseInt(obj.getString("num1"));
				fiveRegisterData_2 += curVal + ",";
				if (i % 3 == 0  || i == 287) {
					fiveRegisterData_4 += (curVal - lastVal_2) + ",";
					lastVal_2 = curVal;
				}
			}
		}
		
		if (length > maxIndex) {
			obj = fiveRegisterData.getJSONObject(maxIndex);
			curNum_2 = Integer.parseInt(obj.getString("num"));
		}
		
		if (length > maxIndex - 1 && maxIndex > 0) {
			obj = fiveRegisterData.getJSONObject(maxIndex - 1);
			fiveminNum_2 = Integer.parseInt(obj.getString("num"));
		}
		
		if (length > maxIndex - 13 && maxIndex > 12) {
			obj = fiveRegisterData.getJSONObject(maxIndex - 13);
			onehourNum_2 = Integer.parseInt(obj.getString("num"));
		}
	}
	
	String fiveminStr_2 = "";
	if (fiveminNum_2 == curNum_2) {
		fiveminStr_2 = fiveminNum_2 + "";
	} else if (fiveminNum_2 - curNum_2 > 0) {
		fiveminStr_2 = fiveminNum_2 + "<span class='grayicon icon-down'></span><font color='#c12121'>" + (fiveminNum_2 - curNum_2) + "</font>";
	} else if (fiveminNum_2 - curNum_2 < 0) {
		fiveminStr_2 = fiveminNum_2 + "<span class='grayicon icon-up'></span><font color='#3a963e'>" + (curNum_2 - fiveminNum_2) + "</font>";
	}
	
	String onehourStr_2 = "";
	if (onehourNum_2 == curNum_2) {
		onehourStr_2 = onehourNum_2 + "";
	} else if (onehourNum_2 - curNum_2 > 0) {
		onehourStr_2 = onehourNum_2 + "<span class='grayicon icon-down'></span><font color='#c12121'>" + (onehourNum_2 - curNum_2) + "</font>";
	} else if (onehourNum_2 - curNum_2 < 0) {
		onehourStr_2 = onehourNum_2 + "<span class='grayicon icon-up'></span><font color='#3a963e'>" + (curNum_2 - onehourNum_2) + "</font>";
	}
	
	JSONObject data_3 = (JSONObject)request.getAttribute("fivePayData");
	JSONArray fivePayData = new JSONArray();
	String fivePayData_1 = "0,";
	String fivePayData_2 = "0,";
	String fivePayData_3 = "0,";
	String fivePayData_4 = "0,";
	int curNum_3 = 0;
	int fiveminNum_3 = 0;
	int onehourNum_3 = 0;
	lastVal_1 = 0; 
	lastVal_2 = 0;
	curVal = 0;
	if (data_1 != null) {
		fivePayData = (JSONArray) data_3.getJSONArray("dataList");
		JSONObject obj;
		int maxIndex = 0;
		int length = fivePayData.length();
		for (int i = 1; i < fivePayData.length(); i++) {
			obj = fivePayData.getJSONObject(i);
			if (obj.has("num")) {
				curVal = Integer.parseInt(obj.getString("num"));
				fivePayData_1 += curVal + ",";
				if (i % 3 == 0 || i == 287) {
					fivePayData_3 += (curVal - lastVal_1) + ",";
					lastVal_1 = curVal;
				}
				maxIndex = i;
			}
				
			if (obj.has("num1")) {
				curVal = Integer.parseInt(obj.getString("num1"));
				fivePayData_2 += curVal + ",";
				if (i % 3 == 0 || i == 287) {
					fivePayData_4 += (curVal - lastVal_2) + ",";
					lastVal_2 = curVal;
				}
			}
		}
		
		if (length > maxIndex) {
			obj = fivePayData.getJSONObject(maxIndex);
			curNum_3 = Integer.parseInt(obj.getString("num"));
		}
		
		if (length > maxIndex - 1 && maxIndex > 0) {
			obj = fivePayData.getJSONObject(maxIndex - 1);
			fiveminNum_3 = Integer.parseInt(obj.getString("num"));
		}
		
		if (length > maxIndex - 13 && maxIndex > 12) {
			obj = fivePayData.getJSONObject(maxIndex - 13);
			onehourNum_3 = Integer.parseInt(obj.getString("num"));
		}
	}
	
	String fiveminStr_3 = "";
	if (fiveminNum_3 == curNum_3) {
		fiveminStr_3 = fiveminNum_3 + "";
	} else if (fiveminNum_3 - curNum_3 > 0) {
		fiveminStr_3 = fiveminNum_3 + "<span class='grayicon icon-down'></span><font color='#c12121'>" + (fiveminNum_3 - curNum_3) + "</font>";
	} else if (fiveminNum_3 - curNum_3 < 0) {
		fiveminStr_3 = fiveminNum_3 + "<span class='grayicon icon-up'></span><font color='#3a963e'>" + (curNum_3 - fiveminNum_3) + "</font>";
	}
	
	String onehourStr_3 = "";
	if (onehourNum_3 == curNum_3) {
		onehourStr_3 = onehourNum_3 + "";
	} else if (onehourNum_3 - curNum_3 > 0) {
		onehourStr_3 = onehourNum_3 + "<span class='grayicon icon-down'></span><font color='#c12121'>" + (onehourNum_3 - curNum_3) + "</font>";
	} else if (onehourNum_3 - curNum_3 < 0) {
		onehourStr_3 = onehourNum_3 + "<span class='grayicon icon-up'></span><font color='#3a963e'>" + (curNum_3 - onehourNum_3) + "</font>";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-24\" data-genuitec-path=\"/OperationAnalysis/WebRoot/header.jsp\">运营分析系统</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(path );
      out.write("/images/favicon.ico\" type=\"image/x-icon\"/>");
      out.write("\r\n");
      out.write("<link type=\"text/css\" href=\"");
      out.print(path);
      out.write("/css/index.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link type=\"text/css\" href=\"");
      out.print(path);
      out.write("/css/datetimepicker.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link type=\"text/css\" href=\"");
      out.print(path);
      out.write("/css/jquery.dataTables.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#timer {\r\n");
      out.write("\t\tcolor: #333333;\r\n");
      out.write("\t\tfont-size: 15px;\r\n");
      out.write("\t\tfont-weight: true;\r\n");
      out.write("\t\tmargin-left: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dataCell_1 {\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tmargin-right: 30px;\r\n");
      out.write("\t\tcolor: #339933;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dataCell_2 {\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tmargin-right: 30px;\r\n");
      out.write("\t\tcolor: #336699;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dataCell_3 {\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tmargin-right: 30px;\r\n");
      out.write("\t\tcolor: #cc3333;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.fiveOnlineModel, .fiveRegModel, .fivePayModel {\r\n");
      out.write("\t\tmargin: 0px 5px 0px 10px;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/js/datetimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(path);
      out.write("/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/js/highcharts.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('.datetimepicker').datetimepicker({\r\n");
      out.write("\t\t\tlang : 'ch',\r\n");
      out.write("\t\t\ttimepicker : false,\r\n");
      out.write("\t\t\tformat : 'Y-m-d',\r\n");
      out.write("\t\t\tformatDate : 'Y-m-d',\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('#chart_1').highcharts(\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tchart : {\r\n");
      out.write("\t\t\t\t\t\ttype : 'spline'\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\t\ttext : ''\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsubtitle : {\r\n");
      out.write("\t\t\t\t\t\ttext : ''\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\txAxis : {\r\n");
      out.write("\t\t\t\t\t\ttype : 'datetime',\r\n");
      out.write("\t\t\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\t\t\ttext : null\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tdateTimeLabelFormats: {\r\n");
      out.write("\t\t\t                day: ' %b月%e日'\r\n");
      out.write("\t\t\t            },\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tyAxis : {\r\n");
      out.write("\t\t\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\t\t\ttext : '在线人数（单位：人）'\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttooltip : {\r\n");
      out.write("\t\t\t\t\t\tcrosshairs : true,\r\n");
      out.write("\t\t\t\t\t\tshared : true,\r\n");
      out.write("\t\t\t\t\t\tuseHTML: true,\r\n");
      out.write("\t\t\t\t\t\tdateTimeLabelFormats: {\r\n");
      out.write("\t\t\t\t\t\t    hour:\"%A, %b月%e日, %H:%M\",\r\n");
      out.write("\t\t\t            },\r\n");
      out.write("\t\t\t\t\t\theaderFormat: ' <span style=\"font-size: 10px\">{point.key}</span><br/>',\r\n");
      out.write("\t\t\t            pointFormat: '<span style=\"color:{series.color}\">\\u25CF</span> {series.name}: <b>{point.y} 人</b><br/>',\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tplotOptions : {\r\n");
      out.write("\t\t\t\t\t\tspline : {\r\n");
      out.write("\t\t\t\t\t\t\tmarker : {\r\n");
      out.write("\t\t\t\t\t\t\t\tenabled: false\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tseries : [ {\r\n");
      out.write("\t\t\t\t\t\tname : '基准时间（");
      out.print( startDate);
      out.write("）',\r\n");
      out.write("\t\t\t\t\t\tpointInterval : 5 * 60 * 1000,\r\n");
      out.write("\t\t\t\t\t\tpointStart : Date.UTC(");
      out.print(y + ", " + m + ", " + d);
      out.write("),\r\n");
      out.write("\t\t\t\t\t\tcolor: '#e15755',\r\n");
      out.write("\t\t\t\t\t\tdata : [ ");
      out.print( fiveOnlineData_1);
      out.write(" ]\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tname : '对比时间（");
      out.print( endDate);
      out.write("）',\r\n");
      out.write("\t\t\t\t\t\tpointInterval : 5 * 60 * 1000,\r\n");
      out.write("\t\t\t\t\t\tpointStart : Date.UTC(");
      out.print(y + ", " + m + ", " + d);
      out.write("),\r\n");
      out.write("\t\t\t\t\t\tcolor: '#578bbb',\r\n");
      out.write("\t\t\t\t\t\tdata : [ ");
      out.print( fiveOnlineData_2);
      out.write(" ]\r\n");
      out.write("\t\t\t\t\t} ],\r\n");
      out.write("\t\t\t\t\tlegend : {\r\n");
      out.write("\t\t\t\t\t\tlabelFormat : '{name}'\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t$('#chart_2').highcharts(\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tchart : {\r\n");
      out.write("\t\t\t\t\t\ttype : 'spline'\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\t\ttext : ''\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsubtitle : {\r\n");
      out.write("\t\t\t\t\t\ttext : ''\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\txAxis : {\r\n");
      out.write("\t\t\t\t\t\ttype : 'datetime',\r\n");
      out.write("\t\t\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\t\t\ttext : null\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tdateTimeLabelFormats: {\r\n");
      out.write("\t\t\t                day: ' %b. %e'\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tyAxis : {\r\n");
      out.write("\t\t\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\t\t\ttext : '注册人数（单位：人）'\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttooltip : {\r\n");
      out.write("\t\t\t\t\t\tcrosshairs : true,\r\n");
      out.write("\t\t\t\t\t\tshared : true,\r\n");
      out.write("\t\t\t\t\t\tuseHTML: true,\r\n");
      out.write("\t\t\t\t\t\theaderFormat: ' <span style=\"font-size: 10px\">{point.key}</span><br/>',\r\n");
      out.write("\t\t\t            pointFormat: '<span style=\"color:{series.color}\">\\u25CF</span> {series.name}: <b>{point.y} 人</b><br/>',\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tplotOptions : {\r\n");
      out.write("\t\t\t\t\t\tspline : {\r\n");
      out.write("\t\t\t\t\t\t\tmarker : {\r\n");
      out.write("\t\t\t\t\t\t\t\tenabled: false\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tseries : [ {\r\n");
      out.write("\t\t\t\t\t\tname : '基准时间（");
      out.print( startDate);
      out.write("）',\r\n");
      out.write("\t\t\t\t\t\tpointInterval : 5 * 60 * 1000,\r\n");
      out.write("\t\t\t\t\t\tpointStart : Date.UTC(");
      out.print(y + ", " + m + ", " + d);
      out.write("),\r\n");
      out.write("\t\t\t\t\t\tcolor: '#e15755',\r\n");
      out.write("\t\t\t\t\t\tdata : [ ");
      out.print( fiveRegisterData_1);
      out.write(" ]\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tname : '对比时间（");
      out.print( endDate);
      out.write("）',\r\n");
      out.write("\t\t\t\t\t\tpointInterval : 5 * 60 * 1000,\r\n");
      out.write("\t\t\t\t\t\tpointStart : Date.UTC(");
      out.print(y + ", " + m + ", " + d);
      out.write("),\r\n");
      out.write("\t\t\t\t\t\tcolor: '#578bbb',\r\n");
      out.write("\t\t\t\t\t\tdata : [ ");
      out.print( fiveRegisterData_2);
      out.write(" ]\r\n");
      out.write("\t\t\t\t\t} ],\r\n");
      out.write("\t\t\t\t\tlegend : {\r\n");
      out.write("\t\t\t\t\t\tlabelFormat : '{name}'\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t$('#chart_3').highcharts(\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tchart : {\r\n");
      out.write("\t\t\t\t\t\ttype : 'spline'\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\t\ttext : ''\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsubtitle : {\r\n");
      out.write("\t\t\t\t\t\ttext : ''\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\txAxis : {\r\n");
      out.write("\t\t\t\t\t\ttype : 'datetime',\r\n");
      out.write("\t\t\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\t\t\ttext : null\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tdateTimeLabelFormats: {\r\n");
      out.write("\t\t\t                day: ' %b. %e'\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tyAxis : {\r\n");
      out.write("\t\t\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\t\t\ttext : '充值金额（单位：元）'\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttooltip : {\r\n");
      out.write("\t\t\t\t\t\tcrosshairs : true,\r\n");
      out.write("\t\t\t\t\t\tshared : true,\r\n");
      out.write("\t\t\t\t\t\tuseHTML: true,\r\n");
      out.write("\t\t\t\t\t\theaderFormat: ' <span style=\"font-size: 10px\">{point.key}</span><br/>',\r\n");
      out.write("\t\t\t            pointFormat: '<span style=\"color:{series.color}\">\\u25CF</span> {series.name}: <b>{point.y} 元</b><br/>',\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tplotOptions : {\r\n");
      out.write("\t\t\t\t\t\tspline : {\r\n");
      out.write("\t\t\t\t\t\t\tmarker : {\r\n");
      out.write("\t\t\t\t\t\t\t\tenabled: false\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tseries : [ {\r\n");
      out.write("\t\t\t\t\t\tname : '基准时间（");
      out.print( startDate);
      out.write("）',\r\n");
      out.write("\t\t\t\t\t\tpointInterval : 5 * 60 * 1000,\r\n");
      out.write("\t\t\t\t\t\tpointStart : Date.UTC(");
      out.print(y + ", " + m + ", " + d);
      out.write("),\r\n");
      out.write("\t\t\t\t\t\tcolor: '#e15755',\r\n");
      out.write("\t\t\t\t\t\tdata : [ ");
      out.print( fivePayData_1);
      out.write(" ]\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tname : '对比时间（");
      out.print( endDate);
      out.write("）',\r\n");
      out.write("\t\t\t\t\t\tpointInterval : 5 * 60 * 1000,\r\n");
      out.write("\t\t\t\t\t\tpointStart : Date.UTC(");
      out.print(y + ", " + m + ", " + d);
      out.write("),\r\n");
      out.write("\t\t\t\t\t\tcolor: '#578bbb',\r\n");
      out.write("\t\t\t\t\t\tdata : [ ");
      out.print( fivePayData_2);
      out.write(" ]\r\n");
      out.write("\t\t\t\t\t} ],\r\n");
      out.write("\t\t\t\t\tlegend : {\r\n");
      out.write("\t\t\t\t\t\tlabelFormat : '{name}'\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar time = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction refresh() {\r\n");
      out.write("\t\t\ttime = time + 1;\r\n");
      out.write("\t\t\tif (time == 300) {\r\n");
      out.write("\t\t\t\t$(\"#request_form\").submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\"#timer\").html((300 - time) + \" 秒后刷新数据\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\tsetInterval(refresh, 1000);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar fiveRegisterData_1 = [");
      out.print(fiveRegisterData_1);
      out.write("];\r\n");
      out.write("\t\tvar fiveRegisterData_2 = [");
      out.print(fiveRegisterData_2);
      out.write("];\r\n");
      out.write("\t\tvar fiveRegisterData_3 = [");
      out.print(fiveRegisterData_3);
      out.write("];\r\n");
      out.write("\t\tvar fiveRegisterData_4 = [");
      out.print(fiveRegisterData_4);
      out.write("];\r\n");
      out.write("\t\tvar fivePayData_1 = [");
      out.print(fivePayData_1);
      out.write("];\r\n");
      out.write("\t\tvar fivePayData_2 = [");
      out.print(fivePayData_2);
      out.write("];\r\n");
      out.write("\t\tvar fivePayData_3 = [");
      out.print(fivePayData_3);
      out.write("];\r\n");
      out.write("\t\tvar fivePayData_4 = [");
      out.print(fivePayData_4);
      out.write("];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".radio_tab_li a\").click(function () {\r\n");
      out.write("\t\t\tvar chart;\r\n");
      out.write("\t\t\tvar val = $(this).attr(\"value\");\r\n");
      out.write("\t\t\tif (val == 21) {\r\n");
      out.write("\t\t\t\t$(this).removeClass().addClass(\"radio_tab_a_current\"); \r\n");
      out.write("\t\t\t\t$(this).parent().next().children().removeClass().addClass(\"radio_tab_a\");\r\n");
      out.write("\t\t\t\tchart = $('#chart_2').highcharts();\r\n");
      out.write("\t\t\t\tchart.series[0].pointInterval = 15 * 60 * 1000;\r\n");
      out.write("\t\t\t\tchart.series[1].pointInterval = 15 * 60 * 1000;\r\n");
      out.write("\t\t\t\tchart.series[0].setData(fiveRegisterData_3);\r\n");
      out.write("\t\t\t\tchart.series[1].setData(fiveRegisterData_4);\r\n");
      out.write("\t\t\t} else if (val == 22) {\r\n");
      out.write("\t\t\t\t$(this).removeClass().addClass(\"radio_tab_a_current\"); \r\n");
      out.write("\t\t\t\t$(this).parent().prev().children().removeClass().addClass(\"radio_tab_a\");\r\n");
      out.write("\t\t\t\tchart = $('#chart_2').highcharts();\r\n");
      out.write("\t\t\t\tchart.series[0].pointInterval = 5 * 60 * 1000;\r\n");
      out.write("\t\t\t\tchart.series[1].pointInterval = 5 * 60 * 1000;\r\n");
      out.write("\t\t\t\tchart.series[0].setData(fiveRegisterData_1);\r\n");
      out.write("\t\t\t\tchart.series[1].setData(fiveRegisterData_2);\r\n");
      out.write("\t\t\t} else if (val == 31) {\r\n");
      out.write("\t\t\t\t$(this).removeClass().addClass(\"radio_tab_a_current\"); \r\n");
      out.write("\t\t\t\t$(this).parent().next().children().removeClass().addClass(\"radio_tab_a\");\r\n");
      out.write("\t\t\t\tchart = $('#chart_3').highcharts();\r\n");
      out.write("\t\t\t\tchart.series[0].pointInterval = 15 * 60 * 1000;\r\n");
      out.write("\t\t\t\tchart.series[1].pointInterval = 15 * 60 * 1000;\r\n");
      out.write("\t\t\t\tchart.series[0].setData(fivePayData_3);\r\n");
      out.write("\t\t\t\tchart.series[1].setData(fivePayData_4);\r\n");
      out.write("\t\t\t} else if (val == 32) {\r\n");
      out.write("\t\t\t\t$(this).removeClass().addClass(\"radio_tab_a_current\"); \r\n");
      out.write("\t\t\t\t$(this).parent().prev().children().removeClass().addClass(\"radio_tab_a\");\r\n");
      out.write("\t\t\t\tchart = $('#chart_3').highcharts();\r\n");
      out.write("\t\t\t\tchart.series[0].pointInterval = 5 * 60 * 1000;\r\n");
      out.write("\t\t\t\tchart.series[1].pointInterval = 5 * 60 * 1000;\r\n");
      out.write("\t\t\t\tchart.series[0].setData(fivePayData_1);\r\n");
      out.write("\t\t\t\tchart.series[1].setData(fivePayData_2);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"55542\",secure:\"55551\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("\r\n");
      out.write("<body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-20\" data-genuitec-path=\"/OperationAnalysis/WebRoot/fiveMinutes.jsp\">\r\n");
      out.write("\t<div class=\"container\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-20\" data-genuitec-path=\"/OperationAnalysis/WebRoot/fiveMinutes.jsp\">\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");

	String agent = (String)request.getSession().getAttribute("agent");
	String gameSite = (String)request.getSession().getAttribute("gameSiteName");
	String server = "";
	String[] serverArray = {}; 
	if (!agent.equals("")) {
		serverArray = agent.split(",");
	} else if (!gameSite.equals("")) {
		serverArray = gameSite.split(",");
	}
	
	int n = serverArray.length;
	
	if (n > 8) 
		n = 9;
	for (int i = 0; i < n; i++) {
		if (i == 8) {
			server += "....." + "、";
		} else {
			server += serverArray[i] + "、";
		}
	}
	
	n = server.length();
	if (n > 0) {
		server = server.substring(0, n - 1);
	}
	
	String username = "";
	User user = (User)request.getSession().getAttribute(request.getSession().getId());
	if (user != null) {
		username = user.getUserName();
	}

      out.write("\r\n");
      out.write("<link type=\"text/css\" href=\"");
      out.print( path);
      out.write("/css/index_header.css\" rel=\"stylesheet\"  data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-27\" data-genuitec-path=\"/OperationAnalysis/WebRoot/index_header.jsp\"/>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<div class=\"header_top\">\r\n");
      out.write("\t\t<span class=\"systemname\">运营分析系统  v1.0.0</span>\r\n");
      out.write("\t\t<div class=\"top_menu\">\r\n");
      out.write("\t\t\t<div class=\"top_menu_item\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print( path);
      out.write("/logout\"><span class=\"icon icon-quit\"></span> 注销 </a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"header_bottom\">\r\n");
      out.write("\t\t<div class=\"bottom_left_menu\">\r\n");
      out.write("\t\t\t<div class=\"bottom_left_menu_item\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print( path);
      out.write("/all?optType=111\"><b>HOME</b></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"bottom_left_menu_item\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print( path);
      out.write("/all?optType=116\" id=\"btn_selectSer\">选择服务器 </a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"server_state\">\r\n");
      out.write("\t\t\t<span>当前服务器 【");
      out.print( server);
      out.write("】</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<span class=\"username\"><span class=\"icon icon-profile\"></span>&nbsp;欢迎您，");
      out.print(username );
      out.write("！</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"left_container\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");

	int pageIndex = 0;
	if (request.getAttribute("pageIndex") != null) {
		pageIndex = Integer.parseInt(request.getAttribute("pageIndex").toString());
	}

      out.write("\r\n");
      out.write("<link type=\"text/css\" href=\"");
      out.print( request.getContextPath());
      out.write("/css/index_menu.css\" rel=\"stylesheet\"  data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-28\" data-genuitec-path=\"/OperationAnalysis/WebRoot/index_menu.jsp\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath());
      out.write("/js/index_menu.js\"> </script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"menu\">\r\n");
      out.write("\t<div id=\"menucontent\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"menu\">\r\n");
      out.write("\t\t\t\t<a href=\"\" onclick=\"return false\" class=\"menuheader\">运营分析</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 101 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/dataAnalysis?optType=");
      out.print( OptTypeConstant.DATA_ANALYSIS_2);
      out.write("\">实时监控</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 102 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/dataAnalysis?optType=");
      out.print( OptTypeConstant.DATA_ANALYSIS_4);
      out.write("\">留存分析</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 105 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/dataAnalysis?optType=");
      out.print( OptTypeConstant.DATA_ANALYSIS_18);
      out.write("\">游戏区看盘</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 106 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/dataAnalysis?optType=");
      out.print( OptTypeConstant.DATA_ANALYSIS_19);
      out.write("\">指标趋势看盘</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 108 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/dataAnalysis?optType=");
      out.print( OptTypeConstant.DATA_ANALYSIS_21);
      out.write("\">在线时长分析</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 109 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/dataAnalysis?optType=");
      out.print( OptTypeConstant.DATA_ANALYSIS_22);
      out.write("\">登录用户构成</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 311 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/behaviorAnalysis?optType=");
      out.print( OptTypeConstant.BEHAVIOR_ANALYSIS_11);
      out.write("\">新手节点流失分析</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"menu\">\r\n");
      out.write("\t\t\t\t<a href=\"\" onclick=\"return false\" class=\"menuheader\">客户管理</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 401 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/accountAnalysis?optType=");
      out.print(OptTypeConstant.ACCOUNT_ANALYSIS_1);
      out.write("\">大客户管理</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 402 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/accountAnalysis?optType=");
      out.print(OptTypeConstant.ACCOUNT_ANALYSIS_2);
      out.write("\">充值订单</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 403 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/accountAnalysis?optType=");
      out.print(OptTypeConstant.ACCOUNT_ANALYSIS_4);
      out.write("\">区服充值数据</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

				if (request.getSession().getAttribute("canUsePay") != null && Boolean.parseBoolean(request.getSession().getAttribute("canUsePay").toString()) == true) {
			 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"menu\">\r\n");
      out.write("\t\t\t\t<a href=\"\" onclick=\"return false\" class=\"menuheader\">付费分析</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 201 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/payAnalysis?optType=");
      out.print(OptTypeConstant.PAY_ANALYSIS_31);
      out.write("\">商城销量分析</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 202 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/payAnalysis?optType=");
      out.print(OptTypeConstant.PAY_ANALYSIS_32);
      out.write("\">元宝消耗分布</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 203 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/payAnalysis?optType=");
      out.print(OptTypeConstant.PAY_ANALYSIS_41);
      out.write("\">首次付费分析</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"");
      out.print( pageIndex == 204 ? "menuitem_current" : "menuitem_none");
      out.write("\" href=\"");
      out.print( request.getContextPath());
      out.write("/payAnalysis?optType=");
      out.print(OptTypeConstant.PAY_ANALYSIS_42);
      out.write("\">首次付费等级分布</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"menu\">\r\n");
      out.write("\t\t\t\t<a href=\"\" onclick=\"return false\" class=\"menuheader\">中控系统</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print( request.getContextPath());
      out.write("/gccServer.jsp\">中控系统</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

				}
				
				if (request.getSession().getAttribute("canUseBeaviour") != null && Boolean.parseBoolean(request.getSession().getAttribute("canUseBeaviour").toString()) == true) {
			 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				}
			 
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"right_container\">\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t<div class=\"content_top\">\r\n");
      out.write("\t\t\t\t\t<form action=\"");
      out.print(path);
      out.write("/dataAnalysis\" id=\"request_form\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"optType\" value=\"");
      out.print( OptTypeConstant.DATA_ANALYSIS_2);
      out.write("\" /> <span>基准时间：</span>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"datetimepicker\" name=\"startDate\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(startDate);
      out.write("\" /> <span>&nbsp;&nbsp;对比时间：</span>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"datetimepicker\" name=\"endDate\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(endDate);
      out.write("\" /><span>&nbsp;&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"确定\" class=\"btn_1\" />\r\n");
      out.write("\t\t\t\t\t\t<span id=\"timer\">300 秒后刷新数据</span>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"content_data\">\r\n");
      out.write("\t\t\t\t\t<div class=\"data_table\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"data_cell\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>在线人数（单位：人）</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"data_value\">最新：");
      out.print(curNum_1 );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t5分钟前：");
      out.print(fiveminStr_1 );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t1小时前：");
      out.print(onehourStr_1 );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"data_cell\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>注册人数（单位：人）</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"data_value\">最新：");
      out.print(curNum_2 );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t5分钟前：");
      out.print(fiveminStr_2 );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t1小时前：");
      out.print(onehourStr_2 );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"data_cell\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>充值金额（单位：元）</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"data_value\">最新：");
      out.print(curNum_3 );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t5分钟前：");
      out.print(fiveminStr_3 );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t1小时前：");
      out.print(onehourStr_3 );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"content_panel\">\r\n");
      out.write("\t\t\t\t\t<div class=\"content_panel_title\">\r\n");
      out.write("\t\t\t\t\t\t<h3>5分钟在线人数分析</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"content_panel_content\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"chart_1\" class=\"chart\" style=\"min-width:500px;height:400px\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"content_panel\">\r\n");
      out.write("\t\t\t\t\t<div class=\"content_panel_title\">\r\n");
      out.write("\t\t\t\t\t\t<h3>5分钟注册人数分析</h3>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"line-height:45px;margin:7px 20px 0px 0px;float:right;\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"radio_tab_ul\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"radio_tab_li\"><a class=\"radio_tab_a\" value=\"21\">分段</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"radio_tab_li\"><a class=\"radio_tab_a_current\" value=\"22\">汇总</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"content_panel_content\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"chart_2\" class=\"chart\" style=\"min-width:500px;height:400px\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"content_panel\">\r\n");
      out.write("\t\t\t\t\t<div class=\"content_panel_title\">\r\n");
      out.write("\t\t\t\t\t\t<h3>5分钟充值金额分析</h3>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"line-height:45px;margin:7px 20px 0px 0px;float:right;\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"radio_tab_ul\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"radio_tab_li\"><a class=\"radio_tab_a\" value=\"31\">分段</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"radio_tab_li\"><a class=\"radio_tab_a_current\" value=\"32\">汇总</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"content_panel_content\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"chart_3\" class=\"chart\" style=\"min-width:500px;height:400px\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<link type=\"text/css\" href=\"");
      out.print( path);
      out.write("/css/index_footer.css\" rel=\"stylesheet\"  data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-26\" data-genuitec-path=\"/OperationAnalysis/WebRoot/index_footer.jsp\"/>\r\n");
      out.write("\r\n");
      out.write("<div class=\"copyright\">\r\n");
      out.write("\t<span>Copyright © 2018 产品团队  粤ICP备XXXXXXX-X号</span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
