// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: market.proto

package com.message;

public final class MarketProto {
  private MarketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MarketItemMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 marketId = 1;
    boolean hasMarketId();
    int getMarketId();
    
    // optional int32 curBuyNum = 2;
    boolean hasCurBuyNum();
    int getCurBuyNum();
  }
  public static final class MarketItemMsg extends
      com.google.protobuf.GeneratedMessage
      implements MarketItemMsgOrBuilder {
    // Use MarketItemMsg.newBuilder() to construct.
    private MarketItemMsg(Builder builder) {
      super(builder);
    }
    private MarketItemMsg(boolean noInit) {}
    
    private static final MarketItemMsg defaultInstance;
    public static MarketItemMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarketItemMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.MarketProto.internal_static_MarketItemMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.MarketProto.internal_static_MarketItemMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 marketId = 1;
    public static final int MARKETID_FIELD_NUMBER = 1;
    private int marketId_;
    public boolean hasMarketId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMarketId() {
      return marketId_;
    }
    
    // optional int32 curBuyNum = 2;
    public static final int CURBUYNUM_FIELD_NUMBER = 2;
    private int curBuyNum_;
    public boolean hasCurBuyNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCurBuyNum() {
      return curBuyNum_;
    }
    
    private void initFields() {
      marketId_ = 0;
      curBuyNum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, marketId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, curBuyNum_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, marketId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, curBuyNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.message.MarketProto.MarketItemMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.MarketProto.MarketItemMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.MarketItemMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.MarketProto.MarketItemMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.MarketItemMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.MarketProto.MarketItemMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.MarketItemMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.MarketProto.MarketItemMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.MarketProto.MarketItemMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.MarketProto.MarketItemMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.MarketProto.MarketItemMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.message.MarketProto.MarketItemMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.MarketProto.internal_static_MarketItemMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.MarketProto.internal_static_MarketItemMsg_fieldAccessorTable;
      }
      
      // Construct using com.message.MarketProto.MarketItemMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        marketId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        curBuyNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.MarketProto.MarketItemMsg.getDescriptor();
      }
      
      public com.message.MarketProto.MarketItemMsg getDefaultInstanceForType() {
        return com.message.MarketProto.MarketItemMsg.getDefaultInstance();
      }
      
      public com.message.MarketProto.MarketItemMsg build() {
        com.message.MarketProto.MarketItemMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.message.MarketProto.MarketItemMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.message.MarketProto.MarketItemMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.message.MarketProto.MarketItemMsg buildPartial() {
        com.message.MarketProto.MarketItemMsg result = new com.message.MarketProto.MarketItemMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.marketId_ = marketId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.curBuyNum_ = curBuyNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.MarketProto.MarketItemMsg) {
          return mergeFrom((com.message.MarketProto.MarketItemMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.message.MarketProto.MarketItemMsg other) {
        if (other == com.message.MarketProto.MarketItemMsg.getDefaultInstance()) return this;
        if (other.hasMarketId()) {
          setMarketId(other.getMarketId());
        }
        if (other.hasCurBuyNum()) {
          setCurBuyNum(other.getCurBuyNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              marketId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              curBuyNum_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 marketId = 1;
      private int marketId_ ;
      public boolean hasMarketId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMarketId() {
        return marketId_;
      }
      public Builder setMarketId(int value) {
        bitField0_ |= 0x00000001;
        marketId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMarketId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        marketId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 curBuyNum = 2;
      private int curBuyNum_ ;
      public boolean hasCurBuyNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCurBuyNum() {
        return curBuyNum_;
      }
      public Builder setCurBuyNum(int value) {
        bitField0_ |= 0x00000002;
        curBuyNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurBuyNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        curBuyNum_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:MarketItemMsg)
    }
    
    static {
      defaultInstance = new MarketItemMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:MarketItemMsg)
  }
  
  public interface C_GetMarketItemListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  public static final class C_GetMarketItemList extends
      com.google.protobuf.GeneratedMessage
      implements C_GetMarketItemListOrBuilder {
    // Use C_GetMarketItemList.newBuilder() to construct.
    private C_GetMarketItemList(Builder builder) {
      super(builder);
    }
    private C_GetMarketItemList(boolean noInit) {}
    
    private static final C_GetMarketItemList defaultInstance;
    public static C_GetMarketItemList getDefaultInstance() {
      return defaultInstance;
    }
    
    public C_GetMarketItemList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.MarketProto.internal_static_C_GetMarketItemList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.MarketProto.internal_static_C_GetMarketItemList_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.message.MarketProto.C_GetMarketItemList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.MarketProto.C_GetMarketItemList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.C_GetMarketItemList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.MarketProto.C_GetMarketItemList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.C_GetMarketItemList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.MarketProto.C_GetMarketItemList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.C_GetMarketItemList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.MarketProto.C_GetMarketItemList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.MarketProto.C_GetMarketItemList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.MarketProto.C_GetMarketItemList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.MarketProto.C_GetMarketItemList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.message.MarketProto.C_GetMarketItemListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.MarketProto.internal_static_C_GetMarketItemList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.MarketProto.internal_static_C_GetMarketItemList_fieldAccessorTable;
      }
      
      // Construct using com.message.MarketProto.C_GetMarketItemList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.MarketProto.C_GetMarketItemList.getDescriptor();
      }
      
      public com.message.MarketProto.C_GetMarketItemList getDefaultInstanceForType() {
        return com.message.MarketProto.C_GetMarketItemList.getDefaultInstance();
      }
      
      public com.message.MarketProto.C_GetMarketItemList build() {
        com.message.MarketProto.C_GetMarketItemList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.message.MarketProto.C_GetMarketItemList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.message.MarketProto.C_GetMarketItemList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.message.MarketProto.C_GetMarketItemList buildPartial() {
        com.message.MarketProto.C_GetMarketItemList result = new com.message.MarketProto.C_GetMarketItemList(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.MarketProto.C_GetMarketItemList) {
          return mergeFrom((com.message.MarketProto.C_GetMarketItemList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.message.MarketProto.C_GetMarketItemList other) {
        if (other == com.message.MarketProto.C_GetMarketItemList.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:C_GetMarketItemList)
    }
    
    static {
      defaultInstance = new C_GetMarketItemList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:C_GetMarketItemList)
  }
  
  public interface S_GetMarketItemListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .MarketItemMsg marketItemList = 1;
    java.util.List<com.message.MarketProto.MarketItemMsg> 
        getMarketItemListList();
    com.message.MarketProto.MarketItemMsg getMarketItemList(int index);
    int getMarketItemListCount();
    java.util.List<? extends com.message.MarketProto.MarketItemMsgOrBuilder> 
        getMarketItemListOrBuilderList();
    com.message.MarketProto.MarketItemMsgOrBuilder getMarketItemListOrBuilder(
        int index);
  }
  public static final class S_GetMarketItemList extends
      com.google.protobuf.GeneratedMessage
      implements S_GetMarketItemListOrBuilder {
    // Use S_GetMarketItemList.newBuilder() to construct.
    private S_GetMarketItemList(Builder builder) {
      super(builder);
    }
    private S_GetMarketItemList(boolean noInit) {}
    
    private static final S_GetMarketItemList defaultInstance;
    public static S_GetMarketItemList getDefaultInstance() {
      return defaultInstance;
    }
    
    public S_GetMarketItemList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.MarketProto.internal_static_S_GetMarketItemList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.MarketProto.internal_static_S_GetMarketItemList_fieldAccessorTable;
    }
    
    // repeated .MarketItemMsg marketItemList = 1;
    public static final int MARKETITEMLIST_FIELD_NUMBER = 1;
    private java.util.List<com.message.MarketProto.MarketItemMsg> marketItemList_;
    public java.util.List<com.message.MarketProto.MarketItemMsg> getMarketItemListList() {
      return marketItemList_;
    }
    public java.util.List<? extends com.message.MarketProto.MarketItemMsgOrBuilder> 
        getMarketItemListOrBuilderList() {
      return marketItemList_;
    }
    public int getMarketItemListCount() {
      return marketItemList_.size();
    }
    public com.message.MarketProto.MarketItemMsg getMarketItemList(int index) {
      return marketItemList_.get(index);
    }
    public com.message.MarketProto.MarketItemMsgOrBuilder getMarketItemListOrBuilder(
        int index) {
      return marketItemList_.get(index);
    }
    
    private void initFields() {
      marketItemList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < marketItemList_.size(); i++) {
        output.writeMessage(1, marketItemList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < marketItemList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, marketItemList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.message.MarketProto.S_GetMarketItemList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.MarketProto.S_GetMarketItemList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.S_GetMarketItemList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.MarketProto.S_GetMarketItemList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.S_GetMarketItemList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.MarketProto.S_GetMarketItemList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.S_GetMarketItemList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.MarketProto.S_GetMarketItemList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.MarketProto.S_GetMarketItemList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.MarketProto.S_GetMarketItemList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.MarketProto.S_GetMarketItemList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.message.MarketProto.S_GetMarketItemListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.MarketProto.internal_static_S_GetMarketItemList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.MarketProto.internal_static_S_GetMarketItemList_fieldAccessorTable;
      }
      
      // Construct using com.message.MarketProto.S_GetMarketItemList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMarketItemListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (marketItemListBuilder_ == null) {
          marketItemList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          marketItemListBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.MarketProto.S_GetMarketItemList.getDescriptor();
      }
      
      public com.message.MarketProto.S_GetMarketItemList getDefaultInstanceForType() {
        return com.message.MarketProto.S_GetMarketItemList.getDefaultInstance();
      }
      
      public com.message.MarketProto.S_GetMarketItemList build() {
        com.message.MarketProto.S_GetMarketItemList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.message.MarketProto.S_GetMarketItemList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.message.MarketProto.S_GetMarketItemList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.message.MarketProto.S_GetMarketItemList buildPartial() {
        com.message.MarketProto.S_GetMarketItemList result = new com.message.MarketProto.S_GetMarketItemList(this);
        int from_bitField0_ = bitField0_;
        if (marketItemListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            marketItemList_ = java.util.Collections.unmodifiableList(marketItemList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.marketItemList_ = marketItemList_;
        } else {
          result.marketItemList_ = marketItemListBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.MarketProto.S_GetMarketItemList) {
          return mergeFrom((com.message.MarketProto.S_GetMarketItemList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.message.MarketProto.S_GetMarketItemList other) {
        if (other == com.message.MarketProto.S_GetMarketItemList.getDefaultInstance()) return this;
        if (marketItemListBuilder_ == null) {
          if (!other.marketItemList_.isEmpty()) {
            if (marketItemList_.isEmpty()) {
              marketItemList_ = other.marketItemList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMarketItemListIsMutable();
              marketItemList_.addAll(other.marketItemList_);
            }
            onChanged();
          }
        } else {
          if (!other.marketItemList_.isEmpty()) {
            if (marketItemListBuilder_.isEmpty()) {
              marketItemListBuilder_.dispose();
              marketItemListBuilder_ = null;
              marketItemList_ = other.marketItemList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              marketItemListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMarketItemListFieldBuilder() : null;
            } else {
              marketItemListBuilder_.addAllMessages(other.marketItemList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.message.MarketProto.MarketItemMsg.Builder subBuilder = com.message.MarketProto.MarketItemMsg.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMarketItemList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .MarketItemMsg marketItemList = 1;
      private java.util.List<com.message.MarketProto.MarketItemMsg> marketItemList_ =
        java.util.Collections.emptyList();
      private void ensureMarketItemListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          marketItemList_ = new java.util.ArrayList<com.message.MarketProto.MarketItemMsg>(marketItemList_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.message.MarketProto.MarketItemMsg, com.message.MarketProto.MarketItemMsg.Builder, com.message.MarketProto.MarketItemMsgOrBuilder> marketItemListBuilder_;
      
      public java.util.List<com.message.MarketProto.MarketItemMsg> getMarketItemListList() {
        if (marketItemListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(marketItemList_);
        } else {
          return marketItemListBuilder_.getMessageList();
        }
      }
      public int getMarketItemListCount() {
        if (marketItemListBuilder_ == null) {
          return marketItemList_.size();
        } else {
          return marketItemListBuilder_.getCount();
        }
      }
      public com.message.MarketProto.MarketItemMsg getMarketItemList(int index) {
        if (marketItemListBuilder_ == null) {
          return marketItemList_.get(index);
        } else {
          return marketItemListBuilder_.getMessage(index);
        }
      }
      public Builder setMarketItemList(
          int index, com.message.MarketProto.MarketItemMsg value) {
        if (marketItemListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarketItemListIsMutable();
          marketItemList_.set(index, value);
          onChanged();
        } else {
          marketItemListBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMarketItemList(
          int index, com.message.MarketProto.MarketItemMsg.Builder builderForValue) {
        if (marketItemListBuilder_ == null) {
          ensureMarketItemListIsMutable();
          marketItemList_.set(index, builderForValue.build());
          onChanged();
        } else {
          marketItemListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMarketItemList(com.message.MarketProto.MarketItemMsg value) {
        if (marketItemListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarketItemListIsMutable();
          marketItemList_.add(value);
          onChanged();
        } else {
          marketItemListBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMarketItemList(
          int index, com.message.MarketProto.MarketItemMsg value) {
        if (marketItemListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarketItemListIsMutable();
          marketItemList_.add(index, value);
          onChanged();
        } else {
          marketItemListBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMarketItemList(
          com.message.MarketProto.MarketItemMsg.Builder builderForValue) {
        if (marketItemListBuilder_ == null) {
          ensureMarketItemListIsMutable();
          marketItemList_.add(builderForValue.build());
          onChanged();
        } else {
          marketItemListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMarketItemList(
          int index, com.message.MarketProto.MarketItemMsg.Builder builderForValue) {
        if (marketItemListBuilder_ == null) {
          ensureMarketItemListIsMutable();
          marketItemList_.add(index, builderForValue.build());
          onChanged();
        } else {
          marketItemListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMarketItemList(
          java.lang.Iterable<? extends com.message.MarketProto.MarketItemMsg> values) {
        if (marketItemListBuilder_ == null) {
          ensureMarketItemListIsMutable();
          super.addAll(values, marketItemList_);
          onChanged();
        } else {
          marketItemListBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMarketItemList() {
        if (marketItemListBuilder_ == null) {
          marketItemList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          marketItemListBuilder_.clear();
        }
        return this;
      }
      public Builder removeMarketItemList(int index) {
        if (marketItemListBuilder_ == null) {
          ensureMarketItemListIsMutable();
          marketItemList_.remove(index);
          onChanged();
        } else {
          marketItemListBuilder_.remove(index);
        }
        return this;
      }
      public com.message.MarketProto.MarketItemMsg.Builder getMarketItemListBuilder(
          int index) {
        return getMarketItemListFieldBuilder().getBuilder(index);
      }
      public com.message.MarketProto.MarketItemMsgOrBuilder getMarketItemListOrBuilder(
          int index) {
        if (marketItemListBuilder_ == null) {
          return marketItemList_.get(index);  } else {
          return marketItemListBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.message.MarketProto.MarketItemMsgOrBuilder> 
           getMarketItemListOrBuilderList() {
        if (marketItemListBuilder_ != null) {
          return marketItemListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(marketItemList_);
        }
      }
      public com.message.MarketProto.MarketItemMsg.Builder addMarketItemListBuilder() {
        return getMarketItemListFieldBuilder().addBuilder(
            com.message.MarketProto.MarketItemMsg.getDefaultInstance());
      }
      public com.message.MarketProto.MarketItemMsg.Builder addMarketItemListBuilder(
          int index) {
        return getMarketItemListFieldBuilder().addBuilder(
            index, com.message.MarketProto.MarketItemMsg.getDefaultInstance());
      }
      public java.util.List<com.message.MarketProto.MarketItemMsg.Builder> 
           getMarketItemListBuilderList() {
        return getMarketItemListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.message.MarketProto.MarketItemMsg, com.message.MarketProto.MarketItemMsg.Builder, com.message.MarketProto.MarketItemMsgOrBuilder> 
          getMarketItemListFieldBuilder() {
        if (marketItemListBuilder_ == null) {
          marketItemListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.message.MarketProto.MarketItemMsg, com.message.MarketProto.MarketItemMsg.Builder, com.message.MarketProto.MarketItemMsgOrBuilder>(
                  marketItemList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          marketItemList_ = null;
        }
        return marketItemListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:S_GetMarketItemList)
    }
    
    static {
      defaultInstance = new S_GetMarketItemList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:S_GetMarketItemList)
  }
  
  public interface C_MarketBuyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 marketId = 1;
    boolean hasMarketId();
    int getMarketId();
    
    // optional int32 num = 2;
    boolean hasNum();
    int getNum();
    
    // optional bool useFlag = 3;
    boolean hasUseFlag();
    boolean getUseFlag();
  }
  public static final class C_MarketBuy extends
      com.google.protobuf.GeneratedMessage
      implements C_MarketBuyOrBuilder {
    // Use C_MarketBuy.newBuilder() to construct.
    private C_MarketBuy(Builder builder) {
      super(builder);
    }
    private C_MarketBuy(boolean noInit) {}
    
    private static final C_MarketBuy defaultInstance;
    public static C_MarketBuy getDefaultInstance() {
      return defaultInstance;
    }
    
    public C_MarketBuy getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.MarketProto.internal_static_C_MarketBuy_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.MarketProto.internal_static_C_MarketBuy_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 marketId = 1;
    public static final int MARKETID_FIELD_NUMBER = 1;
    private int marketId_;
    public boolean hasMarketId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMarketId() {
      return marketId_;
    }
    
    // optional int32 num = 2;
    public static final int NUM_FIELD_NUMBER = 2;
    private int num_;
    public boolean hasNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getNum() {
      return num_;
    }
    
    // optional bool useFlag = 3;
    public static final int USEFLAG_FIELD_NUMBER = 3;
    private boolean useFlag_;
    public boolean hasUseFlag() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getUseFlag() {
      return useFlag_;
    }
    
    private void initFields() {
      marketId_ = 0;
      num_ = 0;
      useFlag_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, marketId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, num_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, useFlag_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, marketId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, useFlag_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.message.MarketProto.C_MarketBuy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.MarketProto.C_MarketBuy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.C_MarketBuy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.MarketProto.C_MarketBuy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.C_MarketBuy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.MarketProto.C_MarketBuy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.C_MarketBuy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.MarketProto.C_MarketBuy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.MarketProto.C_MarketBuy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.MarketProto.C_MarketBuy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.MarketProto.C_MarketBuy prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.message.MarketProto.C_MarketBuyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.MarketProto.internal_static_C_MarketBuy_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.MarketProto.internal_static_C_MarketBuy_fieldAccessorTable;
      }
      
      // Construct using com.message.MarketProto.C_MarketBuy.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        marketId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        useFlag_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.MarketProto.C_MarketBuy.getDescriptor();
      }
      
      public com.message.MarketProto.C_MarketBuy getDefaultInstanceForType() {
        return com.message.MarketProto.C_MarketBuy.getDefaultInstance();
      }
      
      public com.message.MarketProto.C_MarketBuy build() {
        com.message.MarketProto.C_MarketBuy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.message.MarketProto.C_MarketBuy buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.message.MarketProto.C_MarketBuy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.message.MarketProto.C_MarketBuy buildPartial() {
        com.message.MarketProto.C_MarketBuy result = new com.message.MarketProto.C_MarketBuy(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.marketId_ = marketId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.num_ = num_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.useFlag_ = useFlag_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.MarketProto.C_MarketBuy) {
          return mergeFrom((com.message.MarketProto.C_MarketBuy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.message.MarketProto.C_MarketBuy other) {
        if (other == com.message.MarketProto.C_MarketBuy.getDefaultInstance()) return this;
        if (other.hasMarketId()) {
          setMarketId(other.getMarketId());
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (other.hasUseFlag()) {
          setUseFlag(other.getUseFlag());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              marketId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              num_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              useFlag_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 marketId = 1;
      private int marketId_ ;
      public boolean hasMarketId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMarketId() {
        return marketId_;
      }
      public Builder setMarketId(int value) {
        bitField0_ |= 0x00000001;
        marketId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMarketId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        marketId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 num = 2;
      private int num_ ;
      public boolean hasNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getNum() {
        return num_;
      }
      public Builder setNum(int value) {
        bitField0_ |= 0x00000002;
        num_ = value;
        onChanged();
        return this;
      }
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        num_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool useFlag = 3;
      private boolean useFlag_ ;
      public boolean hasUseFlag() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getUseFlag() {
        return useFlag_;
      }
      public Builder setUseFlag(boolean value) {
        bitField0_ |= 0x00000004;
        useFlag_ = value;
        onChanged();
        return this;
      }
      public Builder clearUseFlag() {
        bitField0_ = (bitField0_ & ~0x00000004);
        useFlag_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:C_MarketBuy)
    }
    
    static {
      defaultInstance = new C_MarketBuy(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:C_MarketBuy)
  }
  
  public interface S_MarketBuyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 marketId = 1;
    boolean hasMarketId();
    int getMarketId();
    
    // optional int32 curBuyNum = 2;
    boolean hasCurBuyNum();
    int getCurBuyNum();
  }
  public static final class S_MarketBuy extends
      com.google.protobuf.GeneratedMessage
      implements S_MarketBuyOrBuilder {
    // Use S_MarketBuy.newBuilder() to construct.
    private S_MarketBuy(Builder builder) {
      super(builder);
    }
    private S_MarketBuy(boolean noInit) {}
    
    private static final S_MarketBuy defaultInstance;
    public static S_MarketBuy getDefaultInstance() {
      return defaultInstance;
    }
    
    public S_MarketBuy getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.MarketProto.internal_static_S_MarketBuy_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.MarketProto.internal_static_S_MarketBuy_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 marketId = 1;
    public static final int MARKETID_FIELD_NUMBER = 1;
    private int marketId_;
    public boolean hasMarketId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMarketId() {
      return marketId_;
    }
    
    // optional int32 curBuyNum = 2;
    public static final int CURBUYNUM_FIELD_NUMBER = 2;
    private int curBuyNum_;
    public boolean hasCurBuyNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCurBuyNum() {
      return curBuyNum_;
    }
    
    private void initFields() {
      marketId_ = 0;
      curBuyNum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, marketId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, curBuyNum_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, marketId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, curBuyNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.message.MarketProto.S_MarketBuy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.MarketProto.S_MarketBuy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.S_MarketBuy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.MarketProto.S_MarketBuy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.S_MarketBuy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.MarketProto.S_MarketBuy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.message.MarketProto.S_MarketBuy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.MarketProto.S_MarketBuy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.MarketProto.S_MarketBuy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.MarketProto.S_MarketBuy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.MarketProto.S_MarketBuy prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.message.MarketProto.S_MarketBuyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.MarketProto.internal_static_S_MarketBuy_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.MarketProto.internal_static_S_MarketBuy_fieldAccessorTable;
      }
      
      // Construct using com.message.MarketProto.S_MarketBuy.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        marketId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        curBuyNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.MarketProto.S_MarketBuy.getDescriptor();
      }
      
      public com.message.MarketProto.S_MarketBuy getDefaultInstanceForType() {
        return com.message.MarketProto.S_MarketBuy.getDefaultInstance();
      }
      
      public com.message.MarketProto.S_MarketBuy build() {
        com.message.MarketProto.S_MarketBuy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.message.MarketProto.S_MarketBuy buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.message.MarketProto.S_MarketBuy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.message.MarketProto.S_MarketBuy buildPartial() {
        com.message.MarketProto.S_MarketBuy result = new com.message.MarketProto.S_MarketBuy(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.marketId_ = marketId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.curBuyNum_ = curBuyNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.MarketProto.S_MarketBuy) {
          return mergeFrom((com.message.MarketProto.S_MarketBuy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.message.MarketProto.S_MarketBuy other) {
        if (other == com.message.MarketProto.S_MarketBuy.getDefaultInstance()) return this;
        if (other.hasMarketId()) {
          setMarketId(other.getMarketId());
        }
        if (other.hasCurBuyNum()) {
          setCurBuyNum(other.getCurBuyNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              marketId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              curBuyNum_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 marketId = 1;
      private int marketId_ ;
      public boolean hasMarketId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMarketId() {
        return marketId_;
      }
      public Builder setMarketId(int value) {
        bitField0_ |= 0x00000001;
        marketId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMarketId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        marketId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 curBuyNum = 2;
      private int curBuyNum_ ;
      public boolean hasCurBuyNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCurBuyNum() {
        return curBuyNum_;
      }
      public Builder setCurBuyNum(int value) {
        bitField0_ |= 0x00000002;
        curBuyNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurBuyNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        curBuyNum_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:S_MarketBuy)
    }
    
    static {
      defaultInstance = new S_MarketBuy(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:S_MarketBuy)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MarketItemMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MarketItemMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_C_GetMarketItemList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_C_GetMarketItemList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_S_GetMarketItemList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_S_GetMarketItemList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_C_MarketBuy_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_C_MarketBuy_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_S_MarketBuy_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_S_MarketBuy_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014market.proto\"4\n\rMarketItemMsg\022\020\n\010marke" +
      "tId\030\001 \001(\005\022\021\n\tcurBuyNum\030\002 \001(\005\"\025\n\023C_GetMar" +
      "ketItemList\"=\n\023S_GetMarketItemList\022&\n\016ma" +
      "rketItemList\030\001 \003(\0132\016.MarketItemMsg\"=\n\013C_" +
      "MarketBuy\022\020\n\010marketId\030\001 \001(\005\022\013\n\003num\030\002 \001(\005" +
      "\022\017\n\007useFlag\030\003 \001(\010\"2\n\013S_MarketBuy\022\020\n\010mark" +
      "etId\030\001 \001(\005\022\021\n\tcurBuyNum\030\002 \001(\005B\032\n\013com.mes" +
      "sageB\013MarketProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MarketItemMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MarketItemMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MarketItemMsg_descriptor,
              new java.lang.String[] { "MarketId", "CurBuyNum", },
              com.message.MarketProto.MarketItemMsg.class,
              com.message.MarketProto.MarketItemMsg.Builder.class);
          internal_static_C_GetMarketItemList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_C_GetMarketItemList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_C_GetMarketItemList_descriptor,
              new java.lang.String[] { },
              com.message.MarketProto.C_GetMarketItemList.class,
              com.message.MarketProto.C_GetMarketItemList.Builder.class);
          internal_static_S_GetMarketItemList_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_S_GetMarketItemList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_S_GetMarketItemList_descriptor,
              new java.lang.String[] { "MarketItemList", },
              com.message.MarketProto.S_GetMarketItemList.class,
              com.message.MarketProto.S_GetMarketItemList.Builder.class);
          internal_static_C_MarketBuy_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_C_MarketBuy_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_C_MarketBuy_descriptor,
              new java.lang.String[] { "MarketId", "Num", "UseFlag", },
              com.message.MarketProto.C_MarketBuy.class,
              com.message.MarketProto.C_MarketBuy.Builder.class);
          internal_static_S_MarketBuy_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_S_MarketBuy_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_S_MarketBuy_descriptor,
              new java.lang.String[] { "MarketId", "CurBuyNum", },
              com.message.MarketProto.S_MarketBuy.class,
              com.message.MarketProto.S_MarketBuy.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
