// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sign.proto

package com.message;

public final class SignProto {
  private SignProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SignMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 signNum = 1;
    boolean hasSignNum();
    int getSignNum();
    
    // optional int32 reSignNum = 2;
    boolean hasReSignNum();
    int getReSignNum();
    
    // optional int32 day = 3;
    boolean hasDay();
    int getDay();
    
    // optional int32 state = 4;
    boolean hasState();
    int getState();
    
    // optional int32 conSignDay = 5;
    boolean hasConSignDay();
    int getConSignDay();
    
    // repeated int32 rewardList = 6;
    java.util.List<java.lang.Integer> getRewardListList();
    int getRewardListCount();
    int getRewardList(int index);
  }
  public static final class SignMsg extends
      com.google.protobuf.GeneratedMessage
      implements SignMsgOrBuilder {
    // Use SignMsg.newBuilder() to construct.
    private SignMsg(Builder builder) {
      super(builder);
    }
    private SignMsg(boolean noInit) {}
    
    private static final SignMsg defaultInstance;
    public static SignMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public SignMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.SignProto.internal_static_SignMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.SignProto.internal_static_SignMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 signNum = 1;
    public static final int SIGNNUM_FIELD_NUMBER = 1;
    private int signNum_;
    public boolean hasSignNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSignNum() {
      return signNum_;
    }
    
    // optional int32 reSignNum = 2;
    public static final int RESIGNNUM_FIELD_NUMBER = 2;
    private int reSignNum_;
    public boolean hasReSignNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getReSignNum() {
      return reSignNum_;
    }
    
    // optional int32 day = 3;
    public static final int DAY_FIELD_NUMBER = 3;
    private int day_;
    public boolean hasDay() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getDay() {
      return day_;
    }
    
    // optional int32 state = 4;
    public static final int STATE_FIELD_NUMBER = 4;
    private int state_;
    public boolean hasState() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getState() {
      return state_;
    }
    
    // optional int32 conSignDay = 5;
    public static final int CONSIGNDAY_FIELD_NUMBER = 5;
    private int conSignDay_;
    public boolean hasConSignDay() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getConSignDay() {
      return conSignDay_;
    }
    
    // repeated int32 rewardList = 6;
    public static final int REWARDLIST_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Integer> rewardList_;
    public java.util.List<java.lang.Integer>
        getRewardListList() {
      return rewardList_;
    }
    public int getRewardListCount() {
      return rewardList_.size();
    }
    public int getRewardList(int index) {
      return rewardList_.get(index);
    }
    
    private void initFields() {
      signNum_ = 0;
      reSignNum_ = 0;
      day_ = 0;
      state_ = 0;
      conSignDay_ = 0;
      rewardList_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, signNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, reSignNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, day_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, state_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, conSignDay_);
      }
      for (int i = 0; i < rewardList_.size(); i++) {
        output.writeInt32(6, rewardList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, signNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, reSignNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, day_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, state_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, conSignDay_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < rewardList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(rewardList_.get(i));
        }
        size += dataSize;
        size += 1 * getRewardListList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.message.SignProto.SignMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.SignProto.SignMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.SignMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.SignProto.SignMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.SignMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.SignProto.SignMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.SignMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.SignProto.SignMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.SignProto.SignMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.SignProto.SignMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.SignProto.SignMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.message.SignProto.SignMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.SignProto.internal_static_SignMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.SignProto.internal_static_SignMsg_fieldAccessorTable;
      }
      
      // Construct using com.message.SignProto.SignMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        signNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        reSignNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        day_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        conSignDay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        rewardList_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.SignProto.SignMsg.getDescriptor();
      }
      
      public com.message.SignProto.SignMsg getDefaultInstanceForType() {
        return com.message.SignProto.SignMsg.getDefaultInstance();
      }
      
      public com.message.SignProto.SignMsg build() {
        com.message.SignProto.SignMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.message.SignProto.SignMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.message.SignProto.SignMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.message.SignProto.SignMsg buildPartial() {
        com.message.SignProto.SignMsg result = new com.message.SignProto.SignMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.signNum_ = signNum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reSignNum_ = reSignNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.day_ = day_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.conSignDay_ = conSignDay_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          rewardList_ = java.util.Collections.unmodifiableList(rewardList_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.rewardList_ = rewardList_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.SignProto.SignMsg) {
          return mergeFrom((com.message.SignProto.SignMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.message.SignProto.SignMsg other) {
        if (other == com.message.SignProto.SignMsg.getDefaultInstance()) return this;
        if (other.hasSignNum()) {
          setSignNum(other.getSignNum());
        }
        if (other.hasReSignNum()) {
          setReSignNum(other.getReSignNum());
        }
        if (other.hasDay()) {
          setDay(other.getDay());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasConSignDay()) {
          setConSignDay(other.getConSignDay());
        }
        if (!other.rewardList_.isEmpty()) {
          if (rewardList_.isEmpty()) {
            rewardList_ = other.rewardList_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureRewardListIsMutable();
            rewardList_.addAll(other.rewardList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              signNum_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              reSignNum_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              day_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              state_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              conSignDay_ = input.readInt32();
              break;
            }
            case 48: {
              ensureRewardListIsMutable();
              rewardList_.add(input.readInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addRewardList(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 signNum = 1;
      private int signNum_ ;
      public boolean hasSignNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSignNum() {
        return signNum_;
      }
      public Builder setSignNum(int value) {
        bitField0_ |= 0x00000001;
        signNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearSignNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        signNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 reSignNum = 2;
      private int reSignNum_ ;
      public boolean hasReSignNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getReSignNum() {
        return reSignNum_;
      }
      public Builder setReSignNum(int value) {
        bitField0_ |= 0x00000002;
        reSignNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearReSignNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reSignNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 day = 3;
      private int day_ ;
      public boolean hasDay() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getDay() {
        return day_;
      }
      public Builder setDay(int value) {
        bitField0_ |= 0x00000004;
        day_ = value;
        onChanged();
        return this;
      }
      public Builder clearDay() {
        bitField0_ = (bitField0_ & ~0x00000004);
        day_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 state = 4;
      private int state_ ;
      public boolean hasState() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getState() {
        return state_;
      }
      public Builder setState(int value) {
        bitField0_ |= 0x00000008;
        state_ = value;
        onChanged();
        return this;
      }
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000008);
        state_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 conSignDay = 5;
      private int conSignDay_ ;
      public boolean hasConSignDay() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getConSignDay() {
        return conSignDay_;
      }
      public Builder setConSignDay(int value) {
        bitField0_ |= 0x00000010;
        conSignDay_ = value;
        onChanged();
        return this;
      }
      public Builder clearConSignDay() {
        bitField0_ = (bitField0_ & ~0x00000010);
        conSignDay_ = 0;
        onChanged();
        return this;
      }
      
      // repeated int32 rewardList = 6;
      private java.util.List<java.lang.Integer> rewardList_ = java.util.Collections.emptyList();;
      private void ensureRewardListIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          rewardList_ = new java.util.ArrayList<java.lang.Integer>(rewardList_);
          bitField0_ |= 0x00000020;
         }
      }
      public java.util.List<java.lang.Integer>
          getRewardListList() {
        return java.util.Collections.unmodifiableList(rewardList_);
      }
      public int getRewardListCount() {
        return rewardList_.size();
      }
      public int getRewardList(int index) {
        return rewardList_.get(index);
      }
      public Builder setRewardList(
          int index, int value) {
        ensureRewardListIsMutable();
        rewardList_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addRewardList(int value) {
        ensureRewardListIsMutable();
        rewardList_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllRewardList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureRewardListIsMutable();
        super.addAll(values, rewardList_);
        onChanged();
        return this;
      }
      public Builder clearRewardList() {
        rewardList_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:SignMsg)
    }
    
    static {
      defaultInstance = new SignMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:SignMsg)
  }
  
  public interface C_SignOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  public static final class C_Sign extends
      com.google.protobuf.GeneratedMessage
      implements C_SignOrBuilder {
    // Use C_Sign.newBuilder() to construct.
    private C_Sign(Builder builder) {
      super(builder);
    }
    private C_Sign(boolean noInit) {}
    
    private static final C_Sign defaultInstance;
    public static C_Sign getDefaultInstance() {
      return defaultInstance;
    }
    
    public C_Sign getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.SignProto.internal_static_C_Sign_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.SignProto.internal_static_C_Sign_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.message.SignProto.C_Sign parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.SignProto.C_Sign parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.C_Sign parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.SignProto.C_Sign parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.C_Sign parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.SignProto.C_Sign parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.C_Sign parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.SignProto.C_Sign parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.SignProto.C_Sign parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.SignProto.C_Sign parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.SignProto.C_Sign prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.message.SignProto.C_SignOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.SignProto.internal_static_C_Sign_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.SignProto.internal_static_C_Sign_fieldAccessorTable;
      }
      
      // Construct using com.message.SignProto.C_Sign.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.SignProto.C_Sign.getDescriptor();
      }
      
      public com.message.SignProto.C_Sign getDefaultInstanceForType() {
        return com.message.SignProto.C_Sign.getDefaultInstance();
      }
      
      public com.message.SignProto.C_Sign build() {
        com.message.SignProto.C_Sign result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.message.SignProto.C_Sign buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.message.SignProto.C_Sign result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.message.SignProto.C_Sign buildPartial() {
        com.message.SignProto.C_Sign result = new com.message.SignProto.C_Sign(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.SignProto.C_Sign) {
          return mergeFrom((com.message.SignProto.C_Sign)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.message.SignProto.C_Sign other) {
        if (other == com.message.SignProto.C_Sign.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:C_Sign)
    }
    
    static {
      defaultInstance = new C_Sign(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:C_Sign)
  }
  
  public interface S_SynSignOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .SignMsg signMsg = 1;
    boolean hasSignMsg();
    com.message.SignProto.SignMsg getSignMsg();
    com.message.SignProto.SignMsgOrBuilder getSignMsgOrBuilder();
  }
  public static final class S_SynSign extends
      com.google.protobuf.GeneratedMessage
      implements S_SynSignOrBuilder {
    // Use S_SynSign.newBuilder() to construct.
    private S_SynSign(Builder builder) {
      super(builder);
    }
    private S_SynSign(boolean noInit) {}
    
    private static final S_SynSign defaultInstance;
    public static S_SynSign getDefaultInstance() {
      return defaultInstance;
    }
    
    public S_SynSign getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.SignProto.internal_static_S_SynSign_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.SignProto.internal_static_S_SynSign_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .SignMsg signMsg = 1;
    public static final int SIGNMSG_FIELD_NUMBER = 1;
    private com.message.SignProto.SignMsg signMsg_;
    public boolean hasSignMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.message.SignProto.SignMsg getSignMsg() {
      return signMsg_;
    }
    public com.message.SignProto.SignMsgOrBuilder getSignMsgOrBuilder() {
      return signMsg_;
    }
    
    private void initFields() {
      signMsg_ = com.message.SignProto.SignMsg.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, signMsg_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, signMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.message.SignProto.S_SynSign parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.SignProto.S_SynSign parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.S_SynSign parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.SignProto.S_SynSign parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.S_SynSign parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.SignProto.S_SynSign parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.S_SynSign parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.SignProto.S_SynSign parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.SignProto.S_SynSign parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.SignProto.S_SynSign parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.SignProto.S_SynSign prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.message.SignProto.S_SynSignOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.SignProto.internal_static_S_SynSign_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.SignProto.internal_static_S_SynSign_fieldAccessorTable;
      }
      
      // Construct using com.message.SignProto.S_SynSign.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSignMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (signMsgBuilder_ == null) {
          signMsg_ = com.message.SignProto.SignMsg.getDefaultInstance();
        } else {
          signMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.SignProto.S_SynSign.getDescriptor();
      }
      
      public com.message.SignProto.S_SynSign getDefaultInstanceForType() {
        return com.message.SignProto.S_SynSign.getDefaultInstance();
      }
      
      public com.message.SignProto.S_SynSign build() {
        com.message.SignProto.S_SynSign result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.message.SignProto.S_SynSign buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.message.SignProto.S_SynSign result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.message.SignProto.S_SynSign buildPartial() {
        com.message.SignProto.S_SynSign result = new com.message.SignProto.S_SynSign(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (signMsgBuilder_ == null) {
          result.signMsg_ = signMsg_;
        } else {
          result.signMsg_ = signMsgBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.SignProto.S_SynSign) {
          return mergeFrom((com.message.SignProto.S_SynSign)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.message.SignProto.S_SynSign other) {
        if (other == com.message.SignProto.S_SynSign.getDefaultInstance()) return this;
        if (other.hasSignMsg()) {
          mergeSignMsg(other.getSignMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.message.SignProto.SignMsg.Builder subBuilder = com.message.SignProto.SignMsg.newBuilder();
              if (hasSignMsg()) {
                subBuilder.mergeFrom(getSignMsg());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSignMsg(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .SignMsg signMsg = 1;
      private com.message.SignProto.SignMsg signMsg_ = com.message.SignProto.SignMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.message.SignProto.SignMsg, com.message.SignProto.SignMsg.Builder, com.message.SignProto.SignMsgOrBuilder> signMsgBuilder_;
      public boolean hasSignMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.message.SignProto.SignMsg getSignMsg() {
        if (signMsgBuilder_ == null) {
          return signMsg_;
        } else {
          return signMsgBuilder_.getMessage();
        }
      }
      public Builder setSignMsg(com.message.SignProto.SignMsg value) {
        if (signMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          signMsg_ = value;
          onChanged();
        } else {
          signMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setSignMsg(
          com.message.SignProto.SignMsg.Builder builderForValue) {
        if (signMsgBuilder_ == null) {
          signMsg_ = builderForValue.build();
          onChanged();
        } else {
          signMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeSignMsg(com.message.SignProto.SignMsg value) {
        if (signMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              signMsg_ != com.message.SignProto.SignMsg.getDefaultInstance()) {
            signMsg_ =
              com.message.SignProto.SignMsg.newBuilder(signMsg_).mergeFrom(value).buildPartial();
          } else {
            signMsg_ = value;
          }
          onChanged();
        } else {
          signMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearSignMsg() {
        if (signMsgBuilder_ == null) {
          signMsg_ = com.message.SignProto.SignMsg.getDefaultInstance();
          onChanged();
        } else {
          signMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.message.SignProto.SignMsg.Builder getSignMsgBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSignMsgFieldBuilder().getBuilder();
      }
      public com.message.SignProto.SignMsgOrBuilder getSignMsgOrBuilder() {
        if (signMsgBuilder_ != null) {
          return signMsgBuilder_.getMessageOrBuilder();
        } else {
          return signMsg_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.message.SignProto.SignMsg, com.message.SignProto.SignMsg.Builder, com.message.SignProto.SignMsgOrBuilder> 
          getSignMsgFieldBuilder() {
        if (signMsgBuilder_ == null) {
          signMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.message.SignProto.SignMsg, com.message.SignProto.SignMsg.Builder, com.message.SignProto.SignMsgOrBuilder>(
                  signMsg_,
                  getParentForChildren(),
                  isClean());
          signMsg_ = null;
        }
        return signMsgBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:S_SynSign)
    }
    
    static {
      defaultInstance = new S_SynSign(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:S_SynSign)
  }
  
  public interface C_GetConSignRewardOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 signNum = 1;
    boolean hasSignNum();
    int getSignNum();
  }
  public static final class C_GetConSignReward extends
      com.google.protobuf.GeneratedMessage
      implements C_GetConSignRewardOrBuilder {
    // Use C_GetConSignReward.newBuilder() to construct.
    private C_GetConSignReward(Builder builder) {
      super(builder);
    }
    private C_GetConSignReward(boolean noInit) {}
    
    private static final C_GetConSignReward defaultInstance;
    public static C_GetConSignReward getDefaultInstance() {
      return defaultInstance;
    }
    
    public C_GetConSignReward getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.SignProto.internal_static_C_GetConSignReward_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.SignProto.internal_static_C_GetConSignReward_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 signNum = 1;
    public static final int SIGNNUM_FIELD_NUMBER = 1;
    private int signNum_;
    public boolean hasSignNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSignNum() {
      return signNum_;
    }
    
    private void initFields() {
      signNum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, signNum_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, signNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.message.SignProto.C_GetConSignReward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.SignProto.C_GetConSignReward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.C_GetConSignReward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.SignProto.C_GetConSignReward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.C_GetConSignReward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.SignProto.C_GetConSignReward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.C_GetConSignReward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.SignProto.C_GetConSignReward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.SignProto.C_GetConSignReward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.SignProto.C_GetConSignReward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.SignProto.C_GetConSignReward prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.message.SignProto.C_GetConSignRewardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.SignProto.internal_static_C_GetConSignReward_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.SignProto.internal_static_C_GetConSignReward_fieldAccessorTable;
      }
      
      // Construct using com.message.SignProto.C_GetConSignReward.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        signNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.SignProto.C_GetConSignReward.getDescriptor();
      }
      
      public com.message.SignProto.C_GetConSignReward getDefaultInstanceForType() {
        return com.message.SignProto.C_GetConSignReward.getDefaultInstance();
      }
      
      public com.message.SignProto.C_GetConSignReward build() {
        com.message.SignProto.C_GetConSignReward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.message.SignProto.C_GetConSignReward buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.message.SignProto.C_GetConSignReward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.message.SignProto.C_GetConSignReward buildPartial() {
        com.message.SignProto.C_GetConSignReward result = new com.message.SignProto.C_GetConSignReward(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.signNum_ = signNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.SignProto.C_GetConSignReward) {
          return mergeFrom((com.message.SignProto.C_GetConSignReward)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.message.SignProto.C_GetConSignReward other) {
        if (other == com.message.SignProto.C_GetConSignReward.getDefaultInstance()) return this;
        if (other.hasSignNum()) {
          setSignNum(other.getSignNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              signNum_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 signNum = 1;
      private int signNum_ ;
      public boolean hasSignNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSignNum() {
        return signNum_;
      }
      public Builder setSignNum(int value) {
        bitField0_ |= 0x00000001;
        signNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearSignNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        signNum_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:C_GetConSignReward)
    }
    
    static {
      defaultInstance = new C_GetConSignReward(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:C_GetConSignReward)
  }
  
  public interface S_GetConSignRewardOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 signNum = 1;
    boolean hasSignNum();
    int getSignNum();
  }
  public static final class S_GetConSignReward extends
      com.google.protobuf.GeneratedMessage
      implements S_GetConSignRewardOrBuilder {
    // Use S_GetConSignReward.newBuilder() to construct.
    private S_GetConSignReward(Builder builder) {
      super(builder);
    }
    private S_GetConSignReward(boolean noInit) {}
    
    private static final S_GetConSignReward defaultInstance;
    public static S_GetConSignReward getDefaultInstance() {
      return defaultInstance;
    }
    
    public S_GetConSignReward getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.SignProto.internal_static_S_GetConSignReward_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.SignProto.internal_static_S_GetConSignReward_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 signNum = 1;
    public static final int SIGNNUM_FIELD_NUMBER = 1;
    private int signNum_;
    public boolean hasSignNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSignNum() {
      return signNum_;
    }
    
    private void initFields() {
      signNum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, signNum_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, signNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.message.SignProto.S_GetConSignReward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.SignProto.S_GetConSignReward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.S_GetConSignReward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.message.SignProto.S_GetConSignReward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.S_GetConSignReward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.SignProto.S_GetConSignReward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.message.SignProto.S_GetConSignReward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.SignProto.S_GetConSignReward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.message.SignProto.S_GetConSignReward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.message.SignProto.S_GetConSignReward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.SignProto.S_GetConSignReward prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.message.SignProto.S_GetConSignRewardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.SignProto.internal_static_S_GetConSignReward_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.SignProto.internal_static_S_GetConSignReward_fieldAccessorTable;
      }
      
      // Construct using com.message.SignProto.S_GetConSignReward.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        signNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.SignProto.S_GetConSignReward.getDescriptor();
      }
      
      public com.message.SignProto.S_GetConSignReward getDefaultInstanceForType() {
        return com.message.SignProto.S_GetConSignReward.getDefaultInstance();
      }
      
      public com.message.SignProto.S_GetConSignReward build() {
        com.message.SignProto.S_GetConSignReward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.message.SignProto.S_GetConSignReward buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.message.SignProto.S_GetConSignReward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.message.SignProto.S_GetConSignReward buildPartial() {
        com.message.SignProto.S_GetConSignReward result = new com.message.SignProto.S_GetConSignReward(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.signNum_ = signNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.SignProto.S_GetConSignReward) {
          return mergeFrom((com.message.SignProto.S_GetConSignReward)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.message.SignProto.S_GetConSignReward other) {
        if (other == com.message.SignProto.S_GetConSignReward.getDefaultInstance()) return this;
        if (other.hasSignNum()) {
          setSignNum(other.getSignNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              signNum_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 signNum = 1;
      private int signNum_ ;
      public boolean hasSignNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSignNum() {
        return signNum_;
      }
      public Builder setSignNum(int value) {
        bitField0_ |= 0x00000001;
        signNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearSignNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        signNum_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:S_GetConSignReward)
    }
    
    static {
      defaultInstance = new S_GetConSignReward(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:S_GetConSignReward)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SignMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SignMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_C_Sign_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_C_Sign_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_S_SynSign_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_S_SynSign_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_C_GetConSignReward_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_C_GetConSignReward_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_S_GetConSignReward_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_S_GetConSignReward_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nsign.proto\"q\n\007SignMsg\022\017\n\007signNum\030\001 \001(\005" +
      "\022\021\n\treSignNum\030\002 \001(\005\022\013\n\003day\030\003 \001(\005\022\r\n\005stat" +
      "e\030\004 \001(\005\022\022\n\nconSignDay\030\005 \001(\005\022\022\n\nrewardLis" +
      "t\030\006 \003(\005\"\010\n\006C_Sign\"&\n\tS_SynSign\022\031\n\007signMs" +
      "g\030\001 \001(\0132\010.SignMsg\"%\n\022C_GetConSignReward\022" +
      "\017\n\007signNum\030\001 \001(\005\"%\n\022S_GetConSignReward\022\017" +
      "\n\007signNum\030\001 \001(\005B\030\n\013com.messageB\tSignProt" +
      "o"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SignMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SignMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SignMsg_descriptor,
              new java.lang.String[] { "SignNum", "ReSignNum", "Day", "State", "ConSignDay", "RewardList", },
              com.message.SignProto.SignMsg.class,
              com.message.SignProto.SignMsg.Builder.class);
          internal_static_C_Sign_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_C_Sign_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_C_Sign_descriptor,
              new java.lang.String[] { },
              com.message.SignProto.C_Sign.class,
              com.message.SignProto.C_Sign.Builder.class);
          internal_static_S_SynSign_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_S_SynSign_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_S_SynSign_descriptor,
              new java.lang.String[] { "SignMsg", },
              com.message.SignProto.S_SynSign.class,
              com.message.SignProto.S_SynSign.Builder.class);
          internal_static_C_GetConSignReward_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_C_GetConSignReward_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_C_GetConSignReward_descriptor,
              new java.lang.String[] { "SignNum", },
              com.message.SignProto.C_GetConSignReward.class,
              com.message.SignProto.C_GetConSignReward.Builder.class);
          internal_static_S_GetConSignReward_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_S_GetConSignReward_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_S_GetConSignReward_descriptor,
              new java.lang.String[] { "SignNum", },
              com.message.SignProto.S_GetConSignReward.class,
              com.message.SignProto.S_GetConSignReward.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
