//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class BaseWindowWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(BaseWindow), typeof(FairyGUI.Window));
		L.RegFunction("New", _CreateBaseWindow);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("panel", get_panel, set_panel);
		L.RegVar("contentArea", get_contentArea, set_contentArea);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateBaseWindow(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				string arg0 = ToLua.CheckString(L, 1);
				string arg1 = ToLua.CheckString(L, 2);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 3);
				BaseWindow obj = new BaseWindow(arg0, arg1, arg2);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: BaseWindow.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_panel(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			BaseWindow obj = (BaseWindow)o;
			FairyGUI.GComponent ret = obj.panel;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index panel on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_contentArea(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			BaseWindow obj = (BaseWindow)o;
			FairyGUI.GComponent ret = obj.contentArea;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index contentArea on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_panel(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			BaseWindow obj = (BaseWindow)o;
			FairyGUI.GComponent arg0 = (FairyGUI.GComponent)ToLua.CheckObject(L, 2, typeof(FairyGUI.GComponent));
			obj.panel = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index panel on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_contentArea(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			BaseWindow obj = (BaseWindow)o;
			FairyGUI.GComponent arg0 = (FairyGUI.GComponent)ToLua.CheckObject(L, 2, typeof(FairyGUI.GComponent));
			obj.contentArea = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index contentArea on a nil value" : e.Message);
		}
	}
}

