//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PayMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(PayMgr), typeof(MonoSingleton<PayMgr>));
		L.RegFunction("Pay", Pay);
		L.RegFunction("RestoreProductFailed", RestoreProductFailed);
		L.RegFunction("CancelRestoreProducts", CancelRestoreProducts);
		L.RegFunction("StartBuyProduct", StartBuyProduct);
		L.RegFunction("PayResult", PayResult);
		L.RegFunction("CompletedSKPaymentTransaction", CompletedSKPaymentTransaction);
		L.RegFunction("StartRestoreProduct", StartRestoreProduct);
		L.RegFunction("RestoreTransactions", RestoreTransactions);
		L.RegFunction("RestoreTransaction", RestoreTransaction);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Pay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			PayMgr obj = (PayMgr)ToLua.CheckObject(L, 1, typeof(PayMgr));
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
			string arg3 = ToLua.CheckString(L, 5);
			obj.Pay(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RestoreProductFailed(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PayMgr obj = (PayMgr)ToLua.CheckObject(L, 1, typeof(PayMgr));
			string arg0 = ToLua.CheckString(L, 2);
			obj.RestoreProductFailed(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CancelRestoreProducts(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PayMgr obj = (PayMgr)ToLua.CheckObject(L, 1, typeof(PayMgr));
			obj.CancelRestoreProducts();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartBuyProduct(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			PayMgr obj = (PayMgr)ToLua.CheckObject(L, 1, typeof(PayMgr));
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.StartBuyProduct(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PayResult(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PayMgr obj = (PayMgr)ToLua.CheckObject(L, 1, typeof(PayMgr));
			string arg0 = ToLua.CheckString(L, 2);
			obj.PayResult(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CompletedSKPaymentTransaction(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PayMgr obj = (PayMgr)ToLua.CheckObject(L, 1, typeof(PayMgr));
			string arg0 = ToLua.CheckString(L, 2);
			obj.CompletedSKPaymentTransaction(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartRestoreProduct(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PayMgr obj = (PayMgr)ToLua.CheckObject(L, 1, typeof(PayMgr));
			string arg0 = ToLua.CheckString(L, 2);
			obj.StartRestoreProduct(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RestoreTransactions(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			PayMgr obj = (PayMgr)ToLua.CheckObject(L, 1, typeof(PayMgr));
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.RestoreTransactions(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RestoreTransaction(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			PayMgr obj = (PayMgr)ToLua.CheckObject(L, 1, typeof(PayMgr));
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.RestoreTransaction(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

